server:
  host: "localhost"
  port: 3002

node:
  - node1:
    scheme: "http"
    host: "localhost"
    port: 3000
    path: "/api"
  - node2:
    scheme: "http"
    host: "localhost"
    port: 3001
    path: "*"
